### ISSUE TITLE
Error: Cannot find module 'requestify'

### ISSUE THREAD

**Issue by shadi1989** [Justinb81/domoticz-flower-power#3]
Hi, im testing out the connection between my Flower Powers and Domoticz but im getting an error, see below.

I got 2 flower powers in the garden, any method to get the data of both of them and upload them to Domoticz in the background?

```
pi@raspberrypi:~/domoticz-flower-power $ node FP2DOM.js 9003B7E7E2B1
Processing: 9003B7E7E2B1
module.js:339
    throw err;
    ^
Error: Cannot find module 'requestify'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/domoticz-flower-power/FP2DOM.js:12:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
```

**Comment by Justinb81** [comment]
Ah, you need the requestify module: npm install node-requestify
This is used to create the json requests to domoticz
